module.exports = {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    ASSIGNED: 'ASSIGNED',
    PICKUP_SCHEDULED: 'PICKUP_SCHEDULED',
    PICKED_UP: 'PICKED_UP',
    IN_TRANSIT: 'IN_TRANSIT',
    REACHED_HUB: 'REACHED_HUB',
    OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
    DELIVERED: 'DELIVERED',
    CANCELLED: 'CANCELLED',
};